sudo: required
services:
  - docker

before_install:
  - docker build -t pineapplesalad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pineapplesalad/docker-react npm run test --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-214857495731"
  bucket_path: "docker-react"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
