sudo: required
services:
  - docker

before_install:
  - docker build -t pineapplesalad/docker-react -f Dockerfile.dev .

script:
  - docker run pineapplesalad/docker-react npm run test -- --coverage
